#!/usr/bin/env bash
# run-retrospective-queries.sh — execute the retrospective runbook.
#
# One-shot wrapper around artifacts/metrics/retrospective-queries.sql.
# Streams every labeled query block through psql and writes the output
# to artifacts/metrics/retrospective-raw-<today>.md with headers that
# match the query labels (A1, B3, …) so downstream analysis memos can
# cite the source query directly.
#
# Requirements
#   * psql on PATH
#   * SUPABASE_DB_URL in env (full libpq connection string)
#
# Usage
#   export SUPABASE_DB_URL='postgres://postgres:...@db.<proj>.supabase.co:5432/postgres'
#   bash artifacts/scripts/run-retrospective-queries.sh
#
# Fallback (no psql / no DB creds): pass each labeled block of
# retrospective-queries.sql to mcp__Supabase__execute_sql with
# project_id=ieekjkeayiclprdekxla. The file is organised so any
# single labeled block runs independently.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SQL_FILE="${REPO_ROOT}/artifacts/metrics/retrospective-queries.sql"
TODAY="$(date -u +%Y-%m-%d)"
OUT_FILE="${REPO_ROOT}/artifacts/metrics/retrospective-raw-${TODAY}.md"

if [[ ! -f "${SQL_FILE}" ]]; then
  echo "error: ${SQL_FILE} not found" >&2
  exit 1
fi

if ! command -v psql >/dev/null 2>&1; then
  cat >&2 <<EOF
error: psql not found on PATH.

Install psql (postgresql-client) OR use the MCP fallback:
  copy a labeled block from ${SQL_FILE} and run it via
  mcp__Supabase__execute_sql with project_id=ieekjkeayiclprdekxla.
EOF
  exit 2
fi

if [[ -z "${SUPABASE_DB_URL:-}" ]]; then
  cat >&2 <<EOF
error: SUPABASE_DB_URL not set.

Example:
  export SUPABASE_DB_URL='postgres://postgres:<password>@db.ieekjkeayiclprdekxla.supabase.co:5432/postgres'

The connection string can be found in the Supabase dashboard under
Project Settings -> Database -> Connection string (URI).
EOF
  exit 3
fi

echo "# Retrospective raw output — ${TODAY}" > "${OUT_FILE}"
echo >> "${OUT_FILE}"
echo "Generated by artifacts/scripts/run-retrospective-queries.sh from" >> "${OUT_FILE}"
echo "artifacts/metrics/retrospective-queries.sql." >> "${OUT_FILE}"
echo >> "${OUT_FILE}"
echo '```' >> "${OUT_FILE}"
psql "${SUPABASE_DB_URL}" \
  --no-psqlrc \
  --echo-queries \
  --pset=pager=off \
  --pset=footer=off \
  -v ON_ERROR_STOP=1 \
  -f "${SQL_FILE}" \
  >> "${OUT_FILE}" 2>&1
echo '```' >> "${OUT_FILE}"

echo "wrote: ${OUT_FILE}"
